name:                annealing
version:             0.1.0.0
license:             MIT
author:              "Bim Sherwood"
maintainer:          "bimmosherwood@gmail.com"
copyright:           "2020 Bim Sherwood"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A Simulated Annealing demonstration
category:            Console

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- random
- hashable
- hashmap
- sort

library:
  source-dirs: src

executables:
  annealing-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - annealing

tests:
  annealing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - annealing
